"""create contacts table

Revision ID: d02d4ac50c03
Revises: 44541a0a1167
Create Date: 2026-09-07 13:53:06.995880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types (e.g. UtcDateTime) are rendered by autogenerate as
# fully-qualified names, so the module must be imported here or the migration
# fails with NameError when it runs.
import app.models.types


# revision identifiers, used by Alembic.
revision: str = 'd02d4ac50c03'
down_revision: Union[str, None] = '44541a0a1167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contact_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', app.models.types.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_user_id'], ['users.id'], name=op.f('fk_contacts_contact_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_contacts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'contact_user_id', name=op.f('pk_contacts'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts')
    # ### end Alembic commands ###
