"""create messages and message status

Revision ID: 5294f3a31a0a
Revises: adc46404c32a
Create Date: 2026-09-07 14:37:56.975040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types (e.g. UtcDateTime) are rendered by autogenerate as
# fully-qualified names, so the module must be imported here or the migration
# fails with NameError when it runs.
import app.models.types


# revision identifiers, used by Alembic.
revision: str = '5294f3a31a0a'
down_revision: Union[str, None] = 'adc46404c32a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.Enum('text', name='message_type', native_enum=False, length=32), nullable=False),
    sa.Column('reply_to_id', sa.Integer(), nullable=True),
    sa.Column('created_at', app.models.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('edited_at', app.models.types.UtcDateTime(timezone=True), nullable=True),
    sa.Column('expires_at', app.models.types.UtcDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to_id'], ['messages.id'], name=op.f('fk_messages_reply_to_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_messages_sender_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_conversation_id_created_at', ['conversation_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_reply_to_id'), ['reply_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sender_id'), ['sender_id'], unique=False)

    op.create_table('message_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('sent', 'delivered', 'read', name='delivery_status', native_enum=False, length=32), nullable=False),
    sa.Column('updated_at', app.models.types.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_status_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_message_status_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_status')),
    sa.UniqueConstraint('message_id', 'user_id', name=op.f('uq_message_status_message_id'))
    )
    with op.batch_alter_table('message_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_status_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_status_user_id'))

    op.drop_table('message_status')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_messages_reply_to_id'))
        batch_op.drop_index('ix_messages_conversation_id_created_at')

    op.drop_table('messages')
    # ### end Alembic commands ###
