"""create conversations and participants

Revision ID: adc46404c32a
Revises: d02d4ac50c03
Create Date: 2026-09-07 14:22:51.446547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types (e.g. UtcDateTime) are rendered by autogenerate as
# fully-qualified names, so the module must be imported here or the migration
# fails with NameError when it runs.
import app.models.types


# revision identifiers, used by Alembic.
revision: str = 'adc46404c32a'
down_revision: Union[str, None] = 'd02d4ac50c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('direct', 'group', name='conversation_type', native_enum=False, length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', app.models.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.types.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_table('conversation_participants',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('member', 'admin', name='participant_role', native_enum=False, length=32), nullable=False),
    sa.Column('joined_at', app.models.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('last_read_message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_participants_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversation_participants_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('conversation_id', 'user_id', name=op.f('pk_conversation_participants'))
    )
    with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_participants_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_participants_user_id'))

    op.drop_table('conversation_participants')
    op.drop_table('conversations')
    # ### end Alembic commands ###
