"""index contacts contact_user_id

Revision ID: a7cf82233bf7
Revises: 5294f3a31a0a
Create Date: 2026-09-07 14:47:30.042475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types (e.g. UtcDateTime) are rendered by autogenerate as
# fully-qualified names, so the module must be imported here or the migration
# fails with NameError when it runs.
import app.models.types


# revision identifiers, used by Alembic.
revision: str = 'a7cf82233bf7'
down_revision: Union[str, None] = '5294f3a31a0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_contact_user_id'), ['contact_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_contact_user_id'))

    # ### end Alembic commands ###
